---
title: "Machine Learning Writeup"
author: "rokhrzic"
date: "2 April 2016"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r setup echo=FALSE}

download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", "training.csv")
download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", "testing.csv")

dat <- read.csv("training.csv")
validation <- read.csv("testing.csv")

library(caret)
```

## Exploratory analysis

```{r exploratory}

str(training)

sum(is.na(training))

qplot(classe, data=dat)

dat <- dat[,-c(1:7)]
validation <- validation[,-c(1:7)]

```

## Modelling

```{r exploratory}

inTrain <- createDataPartition(y=dat, p=0.7, list=FALSE)

training <- dat[inTrain]
testing <- dat[-inTrain]

RFmdl <- train(classe~., data=training, method="rf", trainControl(method="cv", number=5))
GBMmdl <- train(classe~., data=training, method="gbm", trainControl(method="cv", number=5))
LDAmdl <- train(classe~., data=training, method="lda", trainControl(method="cv", number=5))

RFprd <- predict(RFmdl, testing)
GBMprd <- predict(GBMmdl, testing)
LDAprd <- predict(LDAmdl, testing)

combined.data <- data.frame(RFprd, GBMprd, LDAprd, testing$classe)

combined.mdl <- train(classe~., data=combined.data, method="rf", trainControl(method="cv", number=5))

combined.prd <- predict(combined.mdl, testing)

```

## In-Sample Evaluation

```{r evaluation}

confusionMatrix(RFprd, testing$classe)$overall['Accuracy']
confusionMatrix(RFprd, testing$classe)$overall['Accuracy']
confusionMatrix(RFprd, testing$classe)$overall['Accuracy']
confusionMatrix(RFprd, testing$classe)$overall['Accuracy']

```

## Out-Sample Evaluation

```{r predict}

RFval <- predict(RFmdl, validation)
GBMval <- predict(GBMmdl, validation)
LDAval <- predict(LDAmdl, validation)

combined.val.dat <- data.frame(RFval, GBMval, LDAval)
combined.val.pred <- predict(combined.mdl, combined.val.dat)

final.pred <- data.frame(RFval, GBMval, LDAval, combined.val.pred)

```

